### PR TITLE
fix: patch fs-extra to fix images on arm64

### LINKED ISSUE #279: [Bug]: signal-desktop does not show images.
### What happened?

When a message contains an image, the image is not shown. Instead, signal-desktop shows a color rectangle with a black circle in the middle that contains an arrow pointing downward. 

signal

When I click on the arrow, a circle cursor is shown briefly, then the arrow reappears. This is aarch64 on an orange pi 5 running ubuntu 
Linux opim 5.10.110-rockchip-rk3588 #1.1.6 SMP Thu Jun 1 21:23:54 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

### What should have happened?

The images should be shown
IMG_6319
(Same chat, snapshot done on iPad)

### Output of `snap info $snap_name`

```shell
cko@opim:~$ snap info signal-desktop
name:      signal-desktop
summary:   Speak Freely - Private Messenger
publisher: Snapcrafters✪
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com//snapcrafters/signal-desktop/issues
license:   AGPL-3.0-only
description: |
  **Note: To use the Signal desktop app, you must first install Signal on your phone.**
  
  Millions of people use Signal every day for free and instantaneous communication anywhere in the
  world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a
  growing set of new features that help you stay connected. Signal's advanced privacy-preserving
  technology is always enabled, so you can focus on sharing the moments that matter with the people
  who matter to you.
  
  - Say anything - State-of-the-art end-to-end encryption (powered by the open source Signal
  Protocol™) keeps your conversations secure. Privacy isn't an optional mode; it's just the way that
  Signal works. Every message, every call, every time.
  - Go fast - Messages are delivered quickly and reliably, even on slow networks. Signal is
  optimized to operate in the most constrained environment possible.
  - Feel free - Signal is a completely independent 501c3 nonprofit. Development is supported by
  users like you. No advertisements. No trackers. No kidding.
  - Be yourself - You can use your existing phone number and address book to securely communicate
  with your friends.
  - Speak up - Whether they live across town or across the ocean, Signal's enhanced audio and video
  quality will make your friends and family feel closer.
  - Whisper in the shadows - Switch to the dark theme if you refuse to see the light.
  
  **Minimize to tray**
  
  Per the request of the Signal developers, this snap does not use the system tray by default. This
  is disabled by default per the request of the Signal developers, because system tray support is
  not stable. Set to `false`, Signal will stop when you close it and will not have a system tray
  icon. You can enable it by running the following command.
  
      snap set signal-desktop tray-icon=true
  
  
  **Are you having issues?**
  
  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: 13 days ago, at 18:32 CET
channels:
  latest/stable:    7.4.0 2024-03-29 (643) 193MB -
  latest/candidate: 7.4.0 2024-03-29 (643) 193MB -
  latest/beta:      ↑                            
  latest/edge:      ↑                            
installed:          7.4.0            (643) 193MB -
```

### Output of `snap connections $snap_name`

```shell
cko@opim:~$ snap connections signal-desktop
Interface               Plug                                   Slot                            Notes
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  :camera                         -
content[gnome-42-2204]  signal-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    :home                           -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
snap    2.61.2
snapd   2.61.2
series  16
ubuntu  22.04
kernel  5.10.110-rockchip-rk3588
```

### Relevant log output

_No response_

### Teminal output of app

```shell
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/643/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/cko/snap/signal-desktop/643/.config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"
Gtk-Message: 00:52:07.505: Failed to load module "xapp-gtk3-module"
Gtk-Message: 00:52:07.506: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Warning: build/dns-fallback.json not build, run `yarn generate`
{"level":30,"time":"2024-04-10T22:52:07.911Z","msg":"got fast localeOverride setting null"}
{"level":30,"time":"2024-04-10T22:52:07.912Z","msg":"app.ready: hour cycle preference: UnknownPreference"}
{"level":30,"time":"2024-04-10T22:52:07.912Z","msg":"app.ready: preferred system locales: en"}
{"level":30,"time":"2024-04-10T22:52:07.913Z","msg":"locale: Supported locales: af-ZA, ar, az-AZ, bg-BG, bn-BD, bs-BA, ca, cs, da, de, el, en, es, et-EE, eu, fa-IR, fi, fr, ga-IE, gl-ES, gu-IN, he, hi-IN, hr-HR, hu, id, it, ja, ka-GE, kk-KZ, km-KH, kn-IN, ko, ky-KG, lt-LT, lv-LV, mk-MK, ml-IN, mr-IN, ms, my, nb, nl, pa-IN, pl, pt-BR, pt-PT, ro-RO, ru, sk-SK, sl-SI, sq-AL, sr, sv, sw, ta-IN, te-IN, th, tl-PH, tr, ug, uk-UA, ur, vi, yue, zh-CN, zh-HK, zh-Hant"}
{"level":30,"time":"2024-04-10T22:52:07.913Z","msg":"locale: Preferred locales: en"}
{"level":30,"time":"2024-04-10T22:52:07.913Z","msg":"locale: Locale Override: null"}
{"level":30,"time":"2024-04-10T22:52:07.916Z","msg":"locale: Matched locale: en"}
{"level":40,"time":"2024-04-10T22:52:07.974Z","msg":"intl.onWarn [@formatjs/intl] \"defaultRichTextElements\" was specified but \"message\" was not pre-compiled. \nPlease consider using \"@formatjs/cli\" to pre-compile your messages for performance.\nFor more details see https://formatjs.io/docs/getting-started/message-distribution"}
{"level":30,"time":"2024-04-10T22:52:07.975Z","msg":"locale: Text info direction for en: ltr"}
{"level":30,"time":"2024-04-10T22:52:07.976Z","msg":"app ready"}
{"level":30,"time":"2024-04-10T22:52:07.977Z","msg":"starting version 7.4.0"}
{"level":30,"time":"2024-04-10T22:52:07.977Z","msg":"media access status [object Undefined] [object Undefined]"}
{"level":30,"time":"2024-04-10T22:52:07.980Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-04-10T22:52:07.985Z","msg":"MainSQL: updateSchema:\n  Current user_version: 1000;\n  Most recent db schema: 1000;\n  SQLite version: 3.42.0;\n  SQLCipher version: 4.5.5 community;\n  (deprecated) schema_version: 441;\n"}
{"level":30,"time":"2024-04-10T22:52:07.993Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-04-10T22:52:07.993Z","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2024-04-10T22:52:07.994Z","msg":"getSystemTraySetting saw --use-tray-icon flag. Returning MinimizeToSystemTray"}
{"level":30,"time":"2024-04-10T22:52:07.995Z","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":1920,\"height\":1006,\"minWidth\":300,\"minHeight\":200,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"devTools\":false,\"spellcheck\":true,\"enableBlinkFeatures\":\"CSSPseudoDir,CSSLogical\",\"enablePreferredSizeMode\":true,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"sandbox\":false,\"contextIsolation\":true,\"preload\":\"[REDACTED]/preload.bundle.js\",\"backgroundThrottling\":true,\"disableBlinkFeatures\":\"Accelerated2dCanvas,AcceleratedSmallCanvases\"},\"icon\":\"[REDACTED]/images/signal-logo-desktop-linux.png\",\"x\":0,\"y\":74}"}
{"level":30,"time":"2024-04-10T22:52:08.107Z","msg":"spellcheck: user locales: [\"en\"]"}
{"level":30,"time":"2024-04-10T22:52:08.107Z","msg":"spellcheck: available spellchecker languages: [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2024-04-10T22:52:08.107Z","msg":"spellcheck: setting languages to: [\"en\"]"}
{"level":30,"time":"2024-04-10T22:52:08.738Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-04-10T22:52:09.815Z","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2024-04-10T22:52:09.818Z","msg":"main window is ready-to-show"}
{"level":30,"time":"2024-04-10T22:52:09.818Z","msg":"showing main window"}
{"level":30,"time":"2024-04-10T22:52:09.832Z","msg":"System tray service: created"}
{"level":30,"time":"2024-04-10T22:52:09.837Z","msg":"System tray service: updating main window. Previously, there was not a window, and now there is"}
{"level":30,"time":"2024-04-10T22:52:09.837Z","msg":"System tray service: rendering no tray"}
{"level":30,"time":"2024-04-10T22:52:09.837Z","msg":"System tray service: enabling"}
{"level":30,"time":"2024-04-10T22:52:09.838Z","msg":"System tray service: rendering the tray"}
{"level":30,"time":"2024-04-10T22:52:09.838Z","msg":"System tray service: creating the tray"}
{"level":30,"time":"2024-04-10T22:52:09.845Z","msg":"Begin ensuring permissions"}
{"level":30,"time":"2024-04-10T22:52:09.855Z","msg":"Ensuring file permissions for 4 files"}
{"level":30,"time":"2024-04-10T22:52:09.863Z","msg":"Finish ensuring permissions in 18ms"}
{"level":30,"time":"2024-04-10T22:52:10.238Z","msg":"MainSQL: slow query getAllStories duration=43ms"}
{"level":30,"time":"2024-04-10T22:52:40.525Z","msg":"Prevent display sleep service: allowing display sleep"}
{"level":30,"time":"2024-04-10T22:52:40.525Z","msg":"Background throttling enabled because no call is active"}
{"level":30,"time":"2024-04-10T22:52:40.965Z","msg":"updater/start: Updates disabled - not starting new version checks"}
{"level":30,"time":"2024-04-10T22:52:40.970Z","msg":"App loaded - time: 32995"}
{"level":30,"time":"2024-04-10T22:52:40.970Z","msg":"SQL init - time: 76"}
{"level":30,"time":"2024-04-10T22:52:40.971Z","msg":"Preload - time: 1052"}
{"level":30,"time":"2024-04-10T22:52:40.971Z","msg":"WebSocket connect - time: 30752"}
{"level":30,"time":"2024-04-10T22:52:40.971Z","msg":"Processed count: 1"}
{"level":30,"time":"2024-04-10T22:52:40.971Z","msg":"Messages per second: 0.8396305625524769"}
{"level":30,"time":"2024-04-10T22:52:42.257Z","msg":"MainSQL: slow query removeMessages duration=100ms"}
{"level":30,"time":"2024-04-10T22:55:08.376Z","msg":"MainSQL: slow query getMessagesNeedingUpgrade duration=108ms"}
{"level":30,"time":"2024-04-10T22:55:08.508Z","msg":"MainSQL: slow query saveMessages duration=53ms"}
```

### PR DESCRIPTION
**Pull request by jnsgruk**
Fixes #279 

Adds a patch to the build which reportedly fixes an issue rendering images on arm64.

@CarstenKochElsdorf perhaps you could build & test?

### CODE REVIEW

**Comment by CarstenKochElsdorf** [comment]
> Fixes #279
> 
> Adds a patch to the build which reportedly fixes an issue rendering images on arm64.
> 
> @CarstenKochElsdorf perhaps you could build & test?

I did. sadly, it still does not work. 

Here are two screen shots from my snap build (bad) and dennisameling build (good):

bad
good

**Comment by CarstenKochElsdorf** [comment]
I have never built a snap before. Maybe I made a mistake? 

Here is what I did:
```
cko@opim:~$ git clone https://github.com/snapcrafters/signal-desktop.git
Cloning into 'signal-desktop'...
remote: Enumerating objects: 1333, done.
remote: Counting objects: 100% (1331/1331), done.
remote: Compressing objects: 100% (661/661), done.
remote: Total 1333 (delta 688), reused 1249 (delta 624), pack-reused 2 (from 1)
Receiving objects: 100% (1333/1333), 346.79 KiB | 4.28 MiB/s, done.
Resolving deltas: 100% (688/688), done.
cko@opim:~$ cd signal-desktop/
cko@opim:~/signal-desktop$ git fetch origin pull/318/head:pr-318
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 1.19 KiB | 173.00 KiB/s, done.
From https://github.com/snapcrafters/signal-desktop
 * [new ref]         refs/pull/318/head -> pr-318
cko@opim:~/signal-desktop$ git checkout pr-318
Switched to branch 'pr-318'
cko@opim:~/signal-desktop$ sudo snap install snapcraft --classic
snapcraft 8.4.1 from Canonical✓ installed
cko@opim:~/signal-desktop$ snapcraft
lxd (5.21/stable) 5.21.2-2f4ba6b from Canonical✓ installed
Failed to install LXD: user must be manually added to 'lxd' group before using LXD.                                                                            
Recommended resolution: Visit https://documentation.ubuntu.com/lxd/en/latest/getting_started/ for instructions on installing and configuring LXD for your operating system.                                                                    
Full execution log: '/home/cko/.local/state/snapcraft/log/snapcraft-20240924-233524.864896.log'                                                                
cko@opim:~/signal-desktop$ sudo usermod -aG lxd $USER
cko@opim:~/signal-desktop$ newgrp lxd
cko@opim:~/signal-desktop$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
The requested storage pool "default" already exists. Please choose another name.
Name of the new storage pool [default=default]: ^C
cko@opim:~/signal-desktop$ snapcraft
Pulling signal-desktop \ (60.4s)                                        Pulling signal-desktop | (60.5s)                                        PuPacked signal-desktop_7.25.0_arm64.snap                                                                                                          
cko@opim:~/signal-desktop$ sudo snap install --dangerous signal-desktop_*.snap
signal-desktop 7.25.0 installed
```

**Comment by jnsgruk** [comment]
Hmm, that looks right. I'll have a poke about and check the patch was applied properly

**Comment by jnsgruk** [comment]
@CarstenKochElsdorf I just updated this slightly, I don't think the patch was applied properly. Can you try a pull and rebuild?

```
cd <your clone>
git pull
snapcraft --verbose

sudo snap remove signal-desktop
sudo snap install ./signal-desktop_7.25.0_amd64 --dangerous
```

**Comment by CarstenKochElsdorf** [comment]
Working now.
Thank you!

**Comment by jnsgruk** [comment]
Nice, should land in `latest/stable` some time today.

**Pull request merged**
