### PR TITLE
Refactor to Core22

### PR DESCRIPTION
**Pull request by galgalesh**

### CODE REVIEW

**Review by kenvandine — COMMENTED** [review]
I haven't tested this yet, but the changes look good

**Comment by galgalesh** [comment]
I've narrowed the side difference down further. It seems the cleanup logic isn't as robust for 22.04 because the path is slightly different.

```shell
# in the snap, it's in lib/x86_64-linux-gnu
merlijn@howard:~/Projects/signal-desktop$ find signal-desktop-core22 -name librsvg-2*
signal-desktop-core22/usr/lib/x86_64-linux-gnu/librsvg-2.so.2.48.0
signal-desktop-core22/usr/lib/x86_64-linux-gnu/librsvg-2.so.2

# in the old platform snap, it was too, it's in lib/x86_64-linux-gnu
merlijn@howard:~$ find /snap/gnome-3-28-1804/current/ -name librsvg-2*
/snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/librsvg-2.so.2
/snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.20

# in the new platform snap, it isn't!
merlijn@howard:~$ find /snap/gnome-42-2204/current/ -name librsvg-2*
/snap/gnome-42-2204/current/usr/lib/librsvg-2.so
/snap/gnome-42-2204/current/usr/lib/librsvg-2.so.2
/snap/gnome-42-2204/current/usr/lib/librsvg-2.so.2.48.0
```

**Comment by galgalesh** [comment]
Not sure why these libs in the content snap have a different path.

Also not sure what the best solution is here. Do I just remove all libraries which match in name, even if they don't in path?

**Review by kenvandine — APPROVED** [review]
Great, thanks!

**Pull request merged**
